### ISSUE TITLE
support keystores on the filesystem instead of only on the classpath

### ISSUE THREAD

**Issue by druppelt** [Hakky54/sslcontext-kickstart#13]
My usecase:
I deploy my application in a docker container in different environments. The appropriate keystore and truststore is mounted in the containers filesystem. In my application I just want to reference "/mnt/certs/truststore.jks", but the current code uses `KeyStoreUtils.class.getClassLoader().getResourceAsStream(keystorePath)` which only searches in the classpath.
I'd like support for absolute paths on the filesystem.

To not break backwards compatibility, maybe first search in the classpath and if nothing is found try reading from the filesystem.

**Comment by Hakky54** [comment]
Hi @druppelt 

Thank you for using this library and mentioning this limitation. The default methods for loading the identity and trust material are indeed using the classpath, however there are also overloaded methods which are capable of loading these files from anywhere on your file system. Could you give the following snippet a shot:
```
Path keyStorePath = Paths.get("/mnt/certs/keystore.jks");
Path trustStorePath = Paths.get("/mnt/certs/keystore.jks");

SSLFactory.builder()
          .withIdentityMaterial(keyStorePath, "keystore-password".toCharArray())
          .withTrustMaterial(trustStorePath, "truststore-password".toCharArray())
          .build();
```

The snippet above will use a different method to load these files, see here for the implementation details [KeyStoreUtils#loadKeyStore](https://github.com/Hakky54/sslcontext-kickstart/blob/66312a073f7c8092baec72fd55cf0053d96da894/sslcontext-kickstart/src/main/java/nl/altindag/sslcontext/util/KeyStoreUtils.java#L33). It will use `Files.newInputStream(keystorePath, StandardOpenOption.READ)` instead of `KeyStoreUtils.class.getClassLoader().getResourceAsStream(keystorePath)`

The following unit test within [SSLFactoryShould](https://github.com/Hakky54/sslcontext-kickstart/blob/66312a073f7c8092baec72fd55cf0053d96da894/sslcontext-kickstart/src/test/java/nl/altindag/sslcontext/SSLFactoryShould.java#L392) also demonstrates/tests loading the keystore files from outside of the classpath. In this case from the home directory of the user.

Please let me know if this solution works for you

**Comment by druppelt** [comment]
Now I feel dumb -.-
Yes that works and is also a good solution, I just overlooked the overloaded method.

Thank you very much for the quick answer and also this awesome library.

**Comment by Hakky54** [comment]
Well I need to thank you! I didn't mentioned this use case at the main documentation and javadoc, so it is perfectly normal that you opened this issue and asked for help. I will update the documentation soon and hopefully it will be also usefull for other developers. Good luck by the way and if you have any other questions please let me know 😊
