### ISSUE TITLE
Keystore password is unnecessary

### ISSUE THREAD

**Issue by winster** [Hakky54/sslcontext-kickstart#14]
Hello,

First of all, thanks for the handy library. I have a suggestion to drop the keystore password as it is redundant (client would have already a Keystore at hand) in the api that takes KeyStore as the first argument.

For example, this is how I use your library.
```
SSLFactory.Builder sslFactoryBuilder = SSLFactory.builder()
                                                         .withDefaultTrustMaterial();
        if ((trustStoreResource != null) && (trustStorePassword != null)) {
            KeyStore trustStore = KeyStore.getInstance("PKCS12");
            trustStore.load(trustStoreResource.getInputStream(),
                            trustStorePassword.toCharArray());
            sslFactoryBuilder.withTrustMaterial(
                trustStore, trustStorePassword.toCharArray());
        }
```
And as you can see, *sslFactoryBuilder.withTrustMaterial(trustStore, **trustStorePassword.toCharArray()**);*, password is not required there.

**Comment by Hakky54** [comment]
Hi @winster 

Thank you for your appreciation! Your remark is valid. It is indeed redundant as you already created your own KeyStore instance and therefor the password would't be required anymore. During the initial design of the library I thought it would be handy to store the passwords in memory, so the developer can still fetch that information afterwords if wanted with the following snippet: 

```java
List<KeyStoreHolder> trustStores = sslFactory.getTrustStores();

KeyStore trustStore = trustStores.get(0).getKeyStore();
char[] trustStorePassword = trustStores.get(0).getKeyStorePassword();
```

So that's the main reason why that method requires a password. But I will create an addtional method which does not require that anymore. 

By the way, in your example snippet you are using an inputstream, Is that the way you are actually loading your KeyStore? And if so I am wondering why you would use the inputstream over the other methods which are available within the SSLFactory.
