### ISSUE TITLE
FenixHostnameVerifier issues

### ISSUE THREAD

**Issue by ecki** [Hakky54/sslcontext-kickstart#230]
Should this be an endsWith()? 

https://github.com/Hakky54/sslcontext-kickstart/blob/c779b17a64f0738d1dd2d2ec9c5e02bc6f5521f3/sslcontext-kickstart/src/main/java/nl/altindag/ssl/hostnameverifier/FenixHostnameVerifier.java#L188

can the !empty be removed if you check for size=2 anyway?

https://github.com/Hakky54/sslcontext-kickstart/blob/c779b17a64f0738d1dd2d2ec9c5e02bc6f5521f3/sslcontext-kickstart/src/main/java/nl/altindag/ssl/hostnameverifier/FenixHostnameVerifier.java#L124

Is this intentionally not checking CN?

https://github.com/Hakky54/sslcontext-kickstart/blob/c779b17a64f0738d1dd2d2ec9c5e02bc6f5521f3/sslcontext-kickstart/src/main/java/nl/altindag/ssl/hostnameverifier/FenixHostnameVerifier.java#L119

i can provide a PR for those issues if youmagree it needs to be fixed.

this verifier should probably also carry a warning that it does not know/forbid patterns in TLDs (*.co.uk instead of *.dom.co.uk or even *.com)?

**Comment by Hakky54** [comment]
Hello, thank you for finding out the parts which can be improved!

> Should this be an endsWith()?

Yes it should indeed be an endsWtih() It seems like I made a mistake there when rewriting this hostnameverifier from the original source code.

> can the !empty be removed if you check for size=2 anyway?

Yes, it can be removed as it is redundant because of the second predicate

> Is this intentionally not checking CN?

This is correct. It tries to get the subject alternative names from the certificate where all of the hostnames should be in. The CN a.k.a. comon name is not part of the hostname and therefor that field should not be used to validate it. So I would suggest not to change that part of the code.

> i can provide a PR for those issues if youmagree it needs to be fixed.

Go for it, I appreciate it!

> this verifier should probably also carry a warning that it does not know/forbid patterns in TLDs (*.co.uk instead of *.dom.co.uk or even *.com)?

Can you explain this part? Maybe with some examples?

**Comment by ecki** [comment]
I think there have been verifiers in the past which only allowed wildcards on subdomains. In order to do that they would need to know what a domain is - and for that they need to look at the public suffix list. But thats not strictly needed and maybe even harmful (wildcards for gTLD allowed) but still something to document.
