### ISSUE TITLE
How do I use this library with JDBC?

### ISSUE THREAD

**Issue by wh5a** [Hakky54/sslcontext-kickstart#298]
Hello,

Thanks for creating this library. I followed the example to load PEM files to build an SSLFactory. What's next? How do I use it to connect to a MySQL server using JDBC securely, with the server CA certificate and the client's private/public key pairs? I tried a few things but couldn't get anywhere. Thank you!

**Comment by Hakky54** [comment]
Hi @wh5a did you found a way to accomplish it?

**Comment by Hakky54** [comment]
It is possible to replace the system SSLContext with the one provided from SSLFactory. Can you try the following snippet:
```
SSLContext.setDefault(sslFactory.getSslContext());
```

**Comment by Hakky54** [comment]
Lets reopen this issue and I will do some investigation on it 😄

**Comment by wh5a** [comment]
Thank you!

**Comment by Hakky54** [comment]
It is indeed not possible. The SSLContext will be configured based on couple of environment properties from the jdbc url. I have created a feature request in the portal of mysql, see here for the ticket: https://bugs.mysql.com/bug.php?id=110463

Let's see what the mysql team will do and whether they will allow to to set a custom sslcontext.

**Comment by Hakky54** [comment]
Hi @wh5a how are you doing? Not quite sure whether you remember this issue, a-lot of time has passed since we have discussed about this topic. While I opened an issue at the mysql bugs page for a feature request, I have not seen any development on their side to enable this kind of feature. Meanwhile I found a way to get it working though, and I thought you might be still interested. So I discovered a mechanisme to bypass the ssl configuration of a library or framework which does not have the option to customize the ssl configuration programatically. I have a small example below.

I use the following docker command to spin up a container:
```
docker run -it -p 33060:3306 --name hakky54-mysql -e MYSQL_ROOT_PASSWORD='secret' mysql
``` 

```java
import nl.altindag.ssl.util.ProviderUtils;

import java.nio.file.Paths;
import java.security.Provider;
import java.security.Security;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;

public class App {

    public static void main(String[] args) {
        SSLFactory sslFactory = SSLFactory.builder()
                .withTrustMaterial(Paths.get("/path/to/your/truststore.p12"), "password".toCharArray())
                .build();

        Provider provider = ProviderUtils.create(sslFactory);
        Security.insertProviderAt(provider, 1);

        String url = "jdbc:mysql://localhost:33060/mysql?verifyServerCertificate=true&useSSL=true&requireSSL=true";
        try (Connection connection = DriverManager.getConnection(url, "root", "secret")) {
            System.out.println("Database connected!");
        } catch (SQLException e) {
            throw new IllegalStateException("Cannot connect the database!", e);
        }
    }

}
```

The `ProviderUtils` is not yet available in the latest release, I will publish it this week.

**Comment by wh5a** [comment]
@Hakky54 That's very cool! Thank you so much for remembering this issue and finding a solution. We ended up with a workaround for this specific issue.
