### ISSUE TITLE
JDK9+ jdeps error

### ISSUE THREAD

**Issue by Ryanznoco** [Hakky54/sslcontext-kickstart#446]
https://github.com/Hakky54/sslcontext-kickstart/blob/313149c3077c3095eff94f7c46d86ff6e883cb33/sslcontext-kickstart-for-apache5/src/main/java/module-info.java#L19

java.lang.module.FindException: Module org.apache.httpcomponents.client5.httpclient5 not found, required by nl.altindag.ssl.apache5

**Comment by Hakky54** [comment]
The module description indeed requires the httpclient5 of apache, however it does not bundle it together in the jar of this module. It is not a transitive dependency, see here: https://github.com/Hakky54/sslcontext-kickstart/blob/313149c3077c3095eff94f7c46d86ff6e883cb33/sslcontext-kickstart-for-apache5/pom.xml#L52

The main reason was because license was not matching exactly with other projects. To prevent issues later I don't redistribute their projects. So if you want to use sslcontext-kickstart-for-apache5 then you also need to add:
```xml
<dependency>
    <groupId>org.apache.httpcomponents.client5</groupId>
    <artifactId>httpclient5</artifactId>
    <version>5.3</version>
</dependency>
```

Can you try adding this dependency and recompile it again, does it resolve your issue?

**Comment by Ryanznoco** [comment]
No, it not work. I find the module-info.java file do not exist in the httpclient5-5.3.jar file.

**Comment by Hakky54** [comment]
Yes, that is correct. The httpclient5 jar does not have the module file and also does not have a module name. The module name which I have in my module file is derrived from the jar name of http client.

I have tried to simulate your behaviour. I created a small project here which contains my library and the apachage http client 5. See here for the project: https://github.com/Hakky54/ssl-apache5-client-poc

It compiles and I can also run it. The pom file has the following depenecies: https://github.com/Hakky54/ssl-apache5-client-poc/blob/master/pom.xml#L18-L32
And the module file has the following requires statements: https://github.com/Hakky54/ssl-apache5-client-poc/blob/master/src/main/java/module-info.java#L3-L5

Can you maybe clone the project and try it out locally and share your results here?

**Comment by Ryanznoco** [comment]
No, still not work. I used io.github.fvarrui/javapackager plugin, when I execute package command, the error occurs. Like this:

[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  3.114 s
[INFO] Finished at: 2024-01-24T23:20:35+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project ssl-apache5-client-poc: Compilation failure: Compilation failure: 
[ERROR] /D:/Workspace/ssl-apache5-client-poc/src/main/java/module-info.java:[3,29] 找不到模块: nl.altindag.ssl.apache5
[ERROR] /D:/Workspace/ssl-apache5-client-poc/src/main/java/module-info.java:[4,47] 找不到模块: org.apache.httpcomponents.client5.httpclient5
[ERROR] /D:/Workspace/ssl-apache5-client-poc/src/main/java/module-info.java:[5,45] 找不到模块: org.apache.httpcomponents.core5.httpcore5
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by Hakky54** [comment]
I did some investigation on the javapackager plugin and it seems that the plugin has issues when modules are being used with dependencies which don't have a module-info java. So basically sslcontext-kickstart-for-apache5 works because it has a module-info file. However it requires a module which is derrived from an automatic name based on the jar name, however that dependency does not have the module-info file so it fails. The solution is to add the configuraiton option:
```xml
<customizedJre>false</customizedJre>
```

I found it from here: https://github.com/fvarrui/JavaPackager/issues/200#issuecomment-1134024485 so it seems to be a known issue for the plugin maintainers.

So my poc project configuration looks like:
```xml
<plugin>
    <groupId>io.github.fvarrui</groupId>
    <artifactId>javapackager</artifactId>
    <version>1.7.5</version>
    <executions>
        <execution>
            <phase>package</phase>
            <goals>
                <goal>package</goal>
            </goals>
            <configuration>
                <mainClass>io.github.hakky54.App</mainClass>
                <bundleJre>true</bundleJre>
                <generateInstaller>true</generateInstaller>
                <administratorRequired>false</administratorRequired>
                <platform>auto</platform>
                <customizedJre>false</customizedJre>
            </configuration>
        </execution>
    </executions>
</plugin>
```

I pushed my changes to https://github.com/Hakky54/ssl-apache5-client-poc can you retry on your side?

**Comment by Ryanznoco** [comment]
It works, thank you!
