### ISSUE TITLE
Trust Anchor not found on Android

### ISSUE THREAD

**Issue by praveenathuru** [Hakky54/sslcontext-kickstart#480]
**Describe the bug**
SSL is not working .

**To Reproduce**
```
@SuppressLint("NewApi")
    private fun httpClientBuilder(): OkHttpClient.Builder {
        val builder = OkHttpClient.Builder()
            .readTimeout(1, TimeUnit.MINUTES)
            .connectTimeout(1, TimeUnit.MINUTES)
            .writeTimeout(1, TimeUnit.MINUTES)
            .addInterceptor(RequestInterceptor(serverManager = serverManager))
            .addInterceptor(chuckerInterceptor)

	// trust manager
        if (ServerManager.cert.isNotEmpty()) {
            val certificateContents = ServerManager.cert.map { ca ->
                String(Base64.decode(ca, Base64.DEFAULT), Charsets.UTF_8)
            }.toTypedArray()
            val trustManager: X509ExtendedTrustManager = PemUtils.parseTrustMaterial(*certificateContents)
            val sslFactory = SSLFactory.builder()
                .withTrustMaterial(trustManager)
                .build()
            builder.sslSocketFactory(
                sslFactory.sslSocketFactory,
                sslFactory.trustManager.orElseThrow()
            )
        }
        return builder
    }
```

Doubts I'm having while using this.
1. If I use this api `.withDefaultTrustMaterial()` the trust issue is gone. But I'm not sure SSL is correctly injected or not in that case. Just because I can see the Request body using Burp suite.
2. Please explain why I'm getting the Trust Anchor not found issue while using this. I want my app to be working for application certificates only.

**Comment by Hakky54** [comment]
`Trust Anchor not found` just means the certificate sent by the counter party, in this case the server, is not trusted by your OkHttp client. So the pem certificate which you try to load seems like it is not matching with the server certificate and therefor failing. If the server certificate is signed by a Certificate Authority and if that Certificate Authority happens to be present in the default trustmaterial option then it will pass and it seems like that is the case for you.

But you only want to trust this specific server instead of using the whole set of CA's. So what I would suggest is to try https://github.com/Hakky54/certificate-ripper and extract the server certificate and load that into the SSLFactory and retry your http call. Can you try that?

**Comment by praveenathuru** [comment]
@Hakky54 Thanks for writing back. Let' say even If I enable the default trust material so issue goes away. But then why I'm able to see the Request Body. (My device has Burp suite certificate installed). I assume if the SSL is working fine, the request sent should be encrypted.

**Comment by Hakky54** [comment]
The body should be encrypted if that is not the case then I would assume the http client is not sending a https request and instead it is sending a http request.

Can you maybe try with a different http client? You can pick any from here https://github.com/Hakky54/sslcontext-kickstart?tab=readme-ov-file#tested-http-clients

It contains example client configuration and example http requests.

**Comment by praveenathuru** [comment]
@Hakky54 I'm using Retrofit with okHttpClient only, I've already attached the okhttp client implementation. Also the request is HTTP only. Not sure what is going wrong with the request.

**Comment by Hakky54** [comment]
I will give a shot with Bup suite, I will ping you back

**Comment by praveenathuru** [comment]
Strange, just because If I do not use the Custom Trust Manager for SSL and use OKHTTP pinnner instead, this is validating the certificate internally and my network calls are not working (Device has Burp Suite Certificate). On normal device it's working fine.
Reference:
<img width="573" alt="Screenshot 2024-04-02 at 9 27 55 AM" src="https://github.com/Hakky54/sslcontext-kickstart/assets/121558741/c2c4f13a-1b34-4310-bdea-6a9dbad3657a">

**So I have no clue why this validation is not working when using Trust Manager.**

@Hakky54  Please look into this if Trust Manager is able to do so. or is there any config which I'm missing in this implementation. As you said earlier `Trust Anchor not found` comes when there is an issue related to the Certificate then why it's working for OKHTTP Pinner. (In this case Certificates are valid). 

PS: I don't have the certificate file available locally just because we are fetching certificates from backend and want to injected them dynamically just to prevent app updates whenever there is an issue related to certificates or they expire. 

**Just another example:** On the same Burp Suite certificate installed device, if you see the background calls of Google services, the request seems to be encrypted.
<img width="812" alt="Screenshot 2024-04-02 at 9 31 15 AM" src="https://github.com/Hakky54/sslcontext-kickstart/assets/121558741/6d714d26-536f-4510-9d02-e930ddeb3a1a">

**Comment by Hakky54** [comment]
> Strange, just because If I do not use the Custom Trust Manager for SSL and use OKHTTP pinnner instead, this is validating the certificate internally and my network calls are not working (Device has Burp Suite Certificate). On normal device it's working fine.

So you are saying that if you use SSL Pinning of OkHttp it is not working at all right? SSL Pinning has some additional certificate validation and it can fail maybe because of that. If you look closely to your exception message it is comparing two sha256 strings and it is failing because of that. I am not an expert in this topic. I would advice to reach out to OkHttp and discuss this topic with them or ask it at stackoverflow with the correct tags, I am pretty sure someone will help you out. If you do so, can you maybe post an update here? I am curious what your findings will be. 

> So I have no clue why this validation is not working when using Trust Manager.

The trustmanager provided by this library does not have certificate pinning. It uses the built in JDK certificate validations from the TrustManager implementation provided by the JDK itself.

> Just another example: On the same Burp Suite certificate installed device, if you see the background calls of Google services, the request seems to be encrypted.

The response from Google is not encrypted, it is encoded in a different format and therefor not reabable. It is encoded as gzip, see also `Accept-Encoding` header field. It has the value `gzip`. So with this information the client app or website needs to unzip it with gzip to get the actual content. This is mostly done to send less data and have less latency.

**Comment by Hakky54** [comment]
I am closing this issue as there is no issue related to the library itself... 
If you have general ssl question or if you want to discuss something feel free to open a discussion
