### ISSUE TITLE
LayeredConnectionSocketFactory is deprecated in Apache httpclient5 5.4

### ISSUE THREAD

**Issue by Athou** [Hakky54/sslcontext-kickstart#560]
**Is your feature request related to a problem? Please describe.**
Since httpclient5 5.4, `LayeredConnectionSocketFactory` is deprecated in favour of the new `TlsSocketStrategy`.

**Describe the solution you'd like**
It'd be nice if a new method `toTlsSocketStrategy` was added to `Apache5SslUtils`.

**Describe alternatives you've considered**
Manually create an instance of `DefaultClientTlsStrategy` from values of my SSLFactory.

Thank you for this fabulous library, it's really useful 😄

**Comment by Hakky54** [comment]
Hi Jérémie,

Thank you for pointing out. It seems like they introduced the new interface since version 5.4 which was released 19th of September, so couple of days ago. I just did a quick analysis and this TlsSocketStrategy looks similar to TlsStrategy. There is a toTlsStrategy method already available for the other interface in the Apache5SslUtils. Any idea what the difference is for those two interfaces as the `DefaultClientTlsStrategy` is implementing both `TlsStrategy` and `TlsSocketStrategy` interface via the `AbstractClientTlsStrategy` class.

**Comment by Athou** [comment]
> Any idea what the difference is for those two interfaces as the `DefaultClientTlsStrategy` is implementing both `TlsStrategy` and `TlsSocketStrategy` interface via the `AbstractClientTlsStrategy` class.

No idea, renovate opened a [PR](https://github.com/Athou/commafeed/pull/1562) but it doesn't build because there is a deprecation warning [here](https://github.com/Athou/commafeed/blob/680d78defef73c498577e50978b8791186ad4bd4/commafeed-server/src/main/java/com/commafeed/backend/HttpGetter.java#L179) and I configured the build to fail on warnings.



> I created a PR by the way to support the new interface, see here: #561
> Please have a look at it and let me now whether this will work for you.

Looks good, thank you!

**Comment by Hakky54** [comment]
Great, I just merged and released it. It is now available in version 8.3.7

**Comment by Athou** [comment]
Awesome, thank you!

https://github.com/Athou/commafeed/commit/21efffa345a79bd2d0fcff890861ea81f6f1bab1
